public class EmployeeWindow extends javax.swing.JFrame {
    
    Birds macau = new Birds("Macua", true);
    Mammals Tiger = new Mammals("Tiger", false);
    Mammals Gorilla = new Mammals("Gorilla", false);
    Reptiles Croc = new Reptiles("Crocodile", false);
    
    Exhibit exhibit1 = new Exhibit(macau,Tiger,Gorilla,Croc);
    
    Birds Eagle = new Birds("Eagle", true);
    Mammals Bear = new Mammals("Bear", false);
    Mammals Deer = new Mammals("Dear", false);
    Reptiles Lizard = new Reptiles("Lizard", false);
    
    Exhibit exhibit2 = new Exhibit(Eagle,Bear,Deer,Lizard);
    
    Birds Hawk = new Birds("Hawk", true);
    Mammals Moose = new Mammals("Moose", false);
    Mammals Squirell = new Mammals("Dear", false);
    Birds Turkey = new Birds("Turkey", false);
    
    Exhibit exhibit3 = new Exhibit(Hawk,Moose,Squirell,Turkey);
    
    Mammals FlyingSquirell = new Mammals("Flying Squirell", false);
    Mammals Bat = new Mammals("Bat", true);
    Reptiles Snake = new Reptiles("Snake", true);
    
    Exhibit exhibit4 = new Exhibit(Hawk,FlyingSquirell,Bat,Snake);
    
    
    Exhibit exhibit5 = new Exhibit(Eagle,Bat,Tiger,Lizard);
    
    Birds Parrot = new Birds("Parrot", true);
    Mammals Lion = new Mammals("Lion", false);
    Mammals Elephant = new Mammals("Elephant", false);
    Reptiles Igunana = new Reptiles("Iguana", false);
    
    Exhibit exhibit6 = new Exhibit(Eagle,Bear,Deer,Lizard);
    
    

    public EmployeeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MoveAnimalTextField = new javax.swing.JTextField();
        ToLocationComboBox = new javax.swing.JComboBox();
        MoveAnimalLabel = new javax.swing.JLabel();
        ToLocationLabel = new javax.swing.JLabel();
        EmployeeExitButton = new javax.swing.JButton();
        E1EmployeeButton = new javax.swing.JButton();
        E2EmployeeButton = new javax.swing.JButton();
        E3EmployeeButton = new javax.swing.JButton();
        E4EmployeeButton = new javax.swing.JButton();
        E5EmployeeButton = new javax.swing.JButton();
        E6EmployeeButton = new javax.swing.JButton();
        EmployeeTextField = new javax.swing.JTextField();
        EmployeeSubmitButton = new javax.swing.JButton();
        EmployeeInstructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MoveAnimalLabel.setText("Move Animal:");

        ToLocationLabel.setText("To Location:");

        EmployeeExitButton.setText("Logout");
        EmployeeExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeExitButtonActionPerformed(evt);
            }
        });

        E1EmployeeButton.setText("E1");
        E1EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1EmployeeButtonActionPerformed(evt);
            }
        });

        E2EmployeeButton.setText("E2");
        E2EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2EmployeeButtonActionPerformed(evt);
            }
        });

        E3EmployeeButton.setText("E3");
        E3EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3EmployeeButtonActionPerformed(evt);
            }
        });

        E4EmployeeButton.setText("E4");
        E4EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4EmployeeButtonActionPerformed(evt);
            }
        });

        E5EmployeeButton.setText("E5");
        E5EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5EmployeeButtonActionPerformed(evt);
            }
        });

        E6EmployeeButton.setText("E6");
        E6EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6EmployeeButtonActionPerformed(evt);
            }
        });

        EmployeeSubmitButton.setText("Submit");
        EmployeeSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSubmitButtonActionPerformed(evt);
            }
        });

        EmployeeInstructions.setText("Select the button of the exhibit you'd like to show the contents of.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(E3EmployeeButton)
                            .addComponent(E1EmployeeButton)
                            .addComponent(E5EmployeeButton))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E2EmployeeButton)
                            .addComponent(E4EmployeeButton)
                            .addComponent(E6EmployeeButton))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeExitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmployeeSubmitButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MoveAnimalLabel)
                                        .addComponent(ToLocationLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MoveAnimalTextField)
                                        .addComponent(ToLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(EmployeeTextField))))
                    .addComponent(EmployeeInstructions))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(E2EmployeeButton)
                        .addGap(29, 29, 29)
                        .addComponent(E4EmployeeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(E1EmployeeButton)
                                    .addGap(29, 29, 29)
                                    .addComponent(E3EmployeeButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(E5EmployeeButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MoveAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MoveAnimalLabel)
                                    .addComponent(E6EmployeeButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToLocationLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeSubmitButton)
                .addGap(69, 69, 69)
                .addComponent(EmployeeExitButton)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeExitButtonActionPerformed
        //Closing the form and returning to the login form
        this.setVisible(false);
        LoginWindow w = new LoginWindow();
        w.setVisible(true);
    }//GEN-LAST:event_EmployeeExitButtonActionPerformed

    private void EmployeeSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSubmitButtonActionPerformed
        //Get the chosen animal and its location from the input text field and combo box
        //Use the info to move the chosen animal out of one of the exhibits and place it in another
        //Clear the input text field
        //Clear the combo box
        //Clear the main text field
        //Set the main text field to show the exhibit that the animal was moved to
    }//GEN-LAST:event_EmployeeSubmitButtonActionPerformed

    private void E1EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit1.getBird1().getName() + "\n"
                                +  exhibit1.getMamm1().getName() + "\n"
                                +  exhibit1.getMamm2().getName() + "\n"
                                +  exhibit1.getReptile().getName() + "\n");
    }//GEN-LAST:event_E1EmployeeButtonActionPerformed

    private void E2EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit2.getBird1().getName() + "\n"
                                +  exhibit2.getMamm1().getName() + "\n"
                                +  exhibit2.getMamm2().getName() + "\n"
                                +  exhibit2.getReptile().getName() + "\n");
    }//GEN-LAST:event_E2EmployeeButtonActionPerformed

    private void E3EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit3.getBird1().getName() + "\n"
                                +  exhibit3.getMamm1().getName() + "\n"
                                +  exhibit3.getMamm2().getName() + "\n"
                                +  exhibit3.getReptile().getName() + "\n");
    }//GEN-LAST:event_E3EmployeeButtonActionPerformed

    private void E4EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit4.getBird1().getName() + "\n"
                                +  exhibit4.getMamm1().getName() + "\n"
                                +  exhibit4.getMamm2().getName() + "\n"
                                +  exhibit4.getReptile().getName() + "\n");
    }//GEN-LAST:event_E4EmployeeButtonActionPerformed

    private void E5EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit5.getBird1().getName() + "\n"
                                +  exhibit5.getMamm1().getName() + "\n"
                                +  exhibit5.getMamm2().getName() + "\n"
                                +  exhibit5.getReptile().getName() + "\n");
    }//GEN-LAST:event_E5EmployeeButtonActionPerformed

    private void E6EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeTextField.setText(exhibit6.getBird1().getName() + "\n"
                                +  exhibit6.getMamm1().getName() + "\n"
                                +  exhibit6.getMamm2().getName() + "\n"
                                +  exhibit6.getReptile().getName() + "\n");
    }//GEN-LAST:event_E6EmployeeButtonActionPerformed

    public static void main(String args[]) {
        // Create and display the form:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E1EmployeeButton;
    private javax.swing.JButton E2EmployeeButton;
    private javax.swing.JButton E3EmployeeButton;
    private javax.swing.JButton E4EmployeeButton;
    private javax.swing.JButton E5EmployeeButton;
    private javax.swing.JButton E6EmployeeButton;
    private javax.swing.JButton EmployeeExitButton;
    private javax.swing.JLabel EmployeeInstructions;
    private javax.swing.JButton EmployeeSubmitButton;
    private javax.swing.JTextField EmployeeTextField;
    private javax.swing.JLabel MoveAnimalLabel;
    private javax.swing.JTextField MoveAnimalTextField;
    private javax.swing.JComboBox ToLocationComboBox;
    private javax.swing.JLabel ToLocationLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
