public class EmployeeWindow extends javax.swing.JFrame {

    public EmployeeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MoveAnimalTextField = new javax.swing.JTextField();
        ToLocationComboBox = new javax.swing.JComboBox();
        MoveAnimalLabel = new javax.swing.JLabel();
        ToLocationLabel = new javax.swing.JLabel();
        EmployeeExitButton = new javax.swing.JButton();
        E1EmployeeButton = new javax.swing.JButton();
        E2EmployeeButton = new javax.swing.JButton();
        E3EmployeeButton = new javax.swing.JButton();
        E4EmployeeButton = new javax.swing.JButton();
        E5EmployeeButton = new javax.swing.JButton();
        E6EmployeeButton = new javax.swing.JButton();
        EmployeeTextField = new javax.swing.JTextField();
        EmployeeSubmitButton = new javax.swing.JButton();
        EmployeeInstructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MoveAnimalLabel.setText("Move Animal:");

        ToLocationLabel.setText("To Location:");

        EmployeeExitButton.setText("Logout");
        EmployeeExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeExitButtonActionPerformed(evt);
            }
        });

        E1EmployeeButton.setText("E1");

        E2EmployeeButton.setText("E2");

        E3EmployeeButton.setText("E3");

        E4EmployeeButton.setText("E4");

        E5EmployeeButton.setText("E5");

        E6EmployeeButton.setText("E6");

        EmployeeSubmitButton.setText("Submit");
        EmployeeSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSubmitButtonActionPerformed(evt);
            }
        });

        EmployeeInstructions.setText("Select the button of the exhibit you'd like to show the contents of.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(E3EmployeeButton)
                            .addComponent(E1EmployeeButton)
                            .addComponent(E5EmployeeButton))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E2EmployeeButton)
                            .addComponent(E4EmployeeButton)
                            .addComponent(E6EmployeeButton))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeExitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmployeeSubmitButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MoveAnimalLabel)
                                        .addComponent(ToLocationLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MoveAnimalTextField)
                                        .addComponent(ToLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(EmployeeTextField))))
                    .addComponent(EmployeeInstructions))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(E2EmployeeButton)
                        .addGap(29, 29, 29)
                        .addComponent(E4EmployeeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(E1EmployeeButton)
                                    .addGap(29, 29, 29)
                                    .addComponent(E3EmployeeButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(E5EmployeeButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmployeeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MoveAnimalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MoveAnimalLabel)
                                    .addComponent(E6EmployeeButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToLocationLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeSubmitButton)
                .addGap(69, 69, 69)
                .addComponent(EmployeeExitButton)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeExitButtonActionPerformed
        //Closing the form and returning to the login form
        this.setVisible(false);
        LoginWindow w = new LoginWindow();
        w.setVisible(true);
    }//GEN-LAST:event_EmployeeExitButtonActionPerformed

    private void EmployeeSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSubmitButtonActionPerformed
        //Get the chosen animal and its location from the input text field and combo box
        //Use the info to move the chosen animal out of one of the exhibits and place it in another
        //Clear the input text field
        //Clear the combo box
        //Clear the main text field
        //Set the main text field to show the exhibit that the animal was moved to
    }//GEN-LAST:event_EmployeeSubmitButtonActionPerformed

    public static void main(String args[]) {
        // Create and display the form:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E1EmployeeButton;
    private javax.swing.JButton E2EmployeeButton;
    private javax.swing.JButton E3EmployeeButton;
    private javax.swing.JButton E4EmployeeButton;
    private javax.swing.JButton E5EmployeeButton;
    private javax.swing.JButton E6EmployeeButton;
    private javax.swing.JButton EmployeeExitButton;
    private javax.swing.JLabel EmployeeInstructions;
    private javax.swing.JButton EmployeeSubmitButton;
    private javax.swing.JTextField EmployeeTextField;
    private javax.swing.JLabel MoveAnimalLabel;
    private javax.swing.JTextField MoveAnimalTextField;
    private javax.swing.JComboBox ToLocationComboBox;
    private javax.swing.JLabel ToLocationLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
