/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author evere
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisitorLoginButton = new javax.swing.JButton();
        EmployeeLoginButton = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VisitorLoginButton.setText("Visitor");
        VisitorLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorLoginButtonActionPerformed(evt);
            }
        });

        EmployeeLoginButton.setText("Employee");
        EmployeeLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeLoginButtonActionPerformed(evt);
            }
        });

        LoginLabel.setText("Hello! Are you a visitor or an employee?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(VisitorLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(EmployeeLoginButton)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeLoginButton)
                    .addComponent(VisitorLoginButton))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisitorLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorLoginButtonActionPerformed
        //Closing the login form and opening the Visitor Window
        this.setVisible(false);
        VisitorWindow w = new VisitorWindow();
        w.setVisible(true);
    }//GEN-LAST:event_VisitorLoginButtonActionPerformed

    private void EmployeeLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeLoginButtonActionPerformed
        //Closing the login form and opening the Employee Window
        this.setVisible(false);
        EmployeeWindow w = new EmployeeWindow();
        w.setVisible(true);
    }//GEN-LAST:event_EmployeeLoginButtonActionPerformed

    public static void main(String args[]) {
        // Create and display the form:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeLoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JButton VisitorLoginButton;
    // End of variables declaration//GEN-END:variables
}
