public class VisitorWindow extends javax.swing.JFrame {

    public VisitorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisitorInstructions = new javax.swing.JLabel();
        VisitorExitButton = new javax.swing.JButton();
        VisitorTextField = new javax.swing.JTextField();
        E1VisitorButton = new javax.swing.JButton();
        E2VisitorButton = new javax.swing.JButton();
        E3VisitorButton = new javax.swing.JButton();
        E4VisitorButton = new javax.swing.JButton();
        E5VisitorButton = new javax.swing.JButton();
        E6VisitorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VisitorInstructions.setText("Click on an exhibit to see which animals are present today!");

        VisitorExitButton.setText("Exit");
        VisitorExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorExitButtonActionPerformed(evt);
            }
        });

        E1VisitorButton.setText("E1");
        E1VisitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1VisitorButtonActionPerformed(evt);
            }
        });

        E2VisitorButton.setText("E2");

        E3VisitorButton.setText("E3");

        E4VisitorButton.setText("E4");

        E5VisitorButton.setText("E5");

        E6VisitorButton.setText("E6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(E3VisitorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(E4VisitorButton)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VisitorInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VisitorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(E1VisitorButton)
                        .addGap(96, 96, 96)
                        .addComponent(E2VisitorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(VisitorExitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(E5VisitorButton)
                        .addGap(149, 149, 149)
                        .addComponent(E6VisitorButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VisitorInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E1VisitorButton)
                    .addComponent(E2VisitorButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(E3VisitorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(E5VisitorButton)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(E4VisitorButton)
                        .addGap(60, 60, 60)
                        .addComponent(E6VisitorButton)
                        .addGap(63, 63, 63)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VisitorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(VisitorExitButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisitorExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorExitButtonActionPerformed
        //Closing the form and returning to the login form
        this.setVisible(false);
        LoginWindow w = new LoginWindow();
        w.setVisible(true);        
    }//GEN-LAST:event_VisitorExitButtonActionPerformed

    private void E1VisitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1VisitorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1VisitorButtonActionPerformed

    public static void main(String args[]) {
        // Create and display the form:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E1VisitorButton;
    private javax.swing.JButton E2VisitorButton;
    private javax.swing.JButton E3VisitorButton;
    private javax.swing.JButton E4VisitorButton;
    private javax.swing.JButton E5VisitorButton;
    private javax.swing.JButton E6VisitorButton;
    private javax.swing.JButton VisitorExitButton;
    private javax.swing.JLabel VisitorInstructions;
    private javax.swing.JTextField VisitorTextField;
    // End of variables declaration//GEN-END:variables
}
